name: Fritbot
responds_to: [fritbot, fb, bot]

connector:
    module: fb-xmpp-connector
    host: 
    conference_host: conference.
    user: 
    resource: 
    password: 
    presence: The Angriest Bot
    rooms: 

web:
    port: 3000

keepalive:
    host: localhost:3000
    interval: 6

module_directory: ./modules